name: batter-env
channels:
  - conda-forge
  - bioconda
  - pytorch
  - defaults
dependencies:
  - _openmp_mutex=4.5=7_kmp_llvm
  - bedtools=2.31.1=h13024bc_3
  - biopython=1.83=py38h01eb140_0
  - blas=2.120=mkl
  - blas-devel=3.9.0=20_linux64_mkl
  - brotli-python=1.1.0=py38h17151c0_1
  - bzip2=1.0.8=hda65f42_8
  - c-ares=1.34.6=hb03c661_0
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - certifi=2024.8.30=pyhd8ed1ab_0
  - cffi=1.17.0=py38heb5c249_0
  - charset-normalizer=3.4.0=pyhd8ed1ab_0
  - click=8.1.7=unix_pyh707e725_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - cudatoolkit=11.0.3=h7761cd4_13
  - dataclasses=0.8=pyhc8e2a94_3
  - filelock=3.16.1=pyhd8ed1ab_0
  - fsspec=2024.10.0=pyhff2d567_0
  - h2=4.1.0=pyhd8ed1ab_0
  - hpack=4.0.0=pyh9f0ad1d_0
  - huggingface_hub=0.26.5=pyhd8ed1ab_0
  - hyperframe=6.0.1=pyhd8ed1ab_0
  - icu=78.2=h33c6efd_0
  - idna=3.10=pyhd8ed1ab_0
  - importlib-metadata=8.5.0=pyha770c72_0
  - importlib_metadata=8.5.0=hd8ed1ab_1
  - joblib=1.4.2=pyhd8ed1ab_0
  - keyutils=1.6.3=hb9d3cd8_0
  - krb5=1.22.2=ha1258a1_0
  - ld_impl_linux-64=2.45.1=default_hbd61a6d_101
  - libblas=3.9.0=20_linux64_mkl
  - libcblas=3.9.0=20_linux64_mkl
  - libcurl=8.18.0=hcf29cc6_1
  - libdeflate=1.25=h17f619e_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libev=4.33=hd590300_2
  - libffi=3.5.2=h3435931_0
  - libgcc=15.2.0=he0feb66_17
  - libgcc-ng=15.2.0=h69a702a_17
  - libgfortran=15.2.0=h69a702a_17
  - libgfortran-ng=15.2.0=h69a702a_17
  - libgfortran5=15.2.0=h68bc16d_17
  - libhwloc=2.12.2=default_hafda6a7_1000
  - libiconv=1.18=h3b78370_2
  - liblapack=3.9.0=20_linux64_mkl
  - liblapacke=3.9.0=20_linux64_mkl
  - liblzma=5.8.2=hb03c661_0
  - liblzma-devel=5.8.2=hb03c661_0
  - libnghttp2=1.67.0=had1ee68_0
  - libnsl=2.0.1=hb9d3cd8_1
  - libsqlite=3.51.2=hf4e2dac_0
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.2.0=h934c35e_17
  - libstdcxx-ng=15.2.0=hdf11a46_17
  - libuuid=2.41.3=h5347b49_0
  - libuv=1.51.0=hb03c661_1
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.15.1=he237659_1
  - libxml2-16=2.15.1=hca6bf5a_1
  - libzlib=1.3.1=hb9d3cd8_2
  - llvm-openmp=21.1.8=h4922eb0_0
  - mkl=2023.2.0=ha770c72_50498
  - mkl-devel=2023.2.0=ha770c72_50498
  - mkl-include=2023.2.0=ha770c72_50498
  - ncurses=6.5=h2d0b736_3
  - ninja=1.13.2=h171cf75_0
  - numpy=1.24.4=py38h59b608b_0
  - openssl=3.6.1=h35e630c_1
  - packaging=26.0=pyhcf101f3_0
  - pandas=2.0.3=py38h01efb38_1
  - pip=24.3.1=pyh8b19718_0
  - pycparser=2.22=pyhd8ed1ab_0
  - pyfaidx=0.7.1=pyh5e36f6f_0
  - pysam=0.22.1=py38h2d19e03_2
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.8.20=h4a871b0_2_cpython
  - python-dateutil=2.9.0=pyhd8ed1ab_0
  - python-tzdata=2024.2=pyhd8ed1ab_0
  - python_abi=3.8=8_cp38
  - pytorch=1.7.0=py3.8_cuda11.0.221_cudnn8.0.3_0
  - pytz=2024.2=pyhd8ed1ab_0
  - pyvcf3=1.0.3=pyhdfd78af_0
  - pyyaml=6.0.2=py38h2019614_0
  - readline=8.3=h853b02a_0
  - regex=2024.7.24=py38h2019614_0
  - requests=2.32.3=pyhd8ed1ab_0
  - sacremoses=0.0.53=pyhd8ed1ab_0
  - setuptools=75.3.0=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - tbb=2021.13.0=hb700be7_5
  - tk=8.6.13=noxft_h366c992_103
  - tokenizers=0.12.1=py38h8bed557_1
  - tqdm=4.67.1=pyhd8ed1ab_0
  - transformers=4.18.0=pyhd8ed1ab_0
  - typing-extensions=4.12.2=hd8ed1ab_0
  - typing_extensions=4.12.2=pyha770c72_0
  - urllib3=2.2.3=pyhd8ed1ab_0
  - wheel=0.45.1=pyhd8ed1ab_0
  - xz=5.8.2=ha02ee65_0
  - xz-gpl-tools=5.8.2=ha02ee65_0
  - xz-tools=5.8.2=hb03c661_0
  - yaml=0.2.5=h280c20c_3
  - zipp=3.21.0=pyhd8ed1ab_0
  - zstandard=0.19.0=py38h0a891b7_0
  - zstd=1.5.7=hb78ec9c_6
