name: batter-env
channels:
  - conda-forge
  - bioconda
  - pytorch
  - defaults
dependencies:
  - _openmp_mutex=4.5
  - bedtools=2.31.1
  - biopython=1.83
  - blas=2.120
  - blas-devel=3.9.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.34.6
  - ca-certificates=2026.1.4
  - certifi=2024.8.30
  - cffi=1.17.0
  - charset-normalizer=3.4.0
  - click=8.1.7
  - colorama=0.4.6
  - cudatoolkit=11.0.3
  - dataclasses=0.8
  - filelock=3.16.1
  - fsspec=2024.10.0
  - h2=4.1.0
  - hpack=4.0.0
  - huggingface_hub=0.26.5
  - hyperframe=6.0.1
  - icu=78.2
  - idna=3.10
  - importlib-metadata=8.5.0
  - importlib_metadata=8.5.0
  - joblib=1.4.2
  - keyutils=1.6.3
  - krb5=1.22.2
  - ld_impl_linux-64=2.45.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=8.18.0
  - libdeflate=1.25
  - libedit=3.1.20250104
  - libev=4.33
  - libffi=3.5.2
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgfortran=15.2.0
  - libgfortran-ng=15.2.0
  - libgfortran5=15.2.0
  - libhwloc=2.12.2
  - libiconv=1.18
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - liblzma=5.8.2
  - liblzma-devel=5.8.2
  - libnghttp2=1.67.0
  - libnsl=2.0.1
  - libsqlite=3.51.2
  - libssh2=1.11.1
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libuuid=2.41.3
  - libuv=1.51.0
  - libxcrypt=4.4.36
  - libxml2=2.15.1
  - libxml2-16=2.15.1
  - libzlib=1.3.1
  - llvm-openmp=21.1.8
  - mkl=2023.2.0
  - mkl-devel=2023.2.0
  - mkl-include=2023.2.0
  - ncurses=6.5
  - ninja=1.13.2
  - numpy=1.24.4
  - openssl=3.6.1
  - packaging=26.0
  - pandas=2.0.3
  - pip=24.3.1
  - pycparser=2.22
  - pyfaidx=0.7.1
  - pysam=0.22.1
  - pysocks=1.7.1
  - python=3.8.20
  - python-dateutil=2.9.0
  - python-tzdata=2024.2
  - python_abi=3.8
  - pytorch=1.7.0
  - pytz=2024.2
  - pyvcf3=1.0.3
  - pyyaml=6.0.2
  - readline=8.3
  - regex=2024.7.24
  - requests=2.32.3
  - sacremoses=0.0.53
  - setuptools=75.3.0
  - six=1.16.0
  - tbb=2021.13.0
  - tk=8.6.13
  - tokenizers=0.12.1
  - tqdm=4.67.1
  - transformers=4.18.0
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - urllib3=2.2.3
  - wheel=0.45.1
  - xz=5.8.2
  - xz-gpl-tools=5.8.2
  - xz-tools=5.8.2
  - yaml=0.2.5
  - zipp=3.21.0
  - zstandard=0.19.0
  - zstd=1.5.7
prefix: /data_hdd/home/jinyunfan/miniconda3/envs/batter-env
